### ISSUE TITLE
Executable not found, proposed : avprobe, ffprobe

### ISSUE THREAD

**Issue by SergeyKozlov** [emgag/video-thumbnail-sprite#8]
I use the **PHP-FFMpeg** in my project.
To create a new instance of the **ffmpeg**, I use this code:
```
$ffmpeg = FFMpeg\FFMpeg::create(array(
            'ffmpeg.binaries' => '/usr/bin/ffmpeg',
            'ffprobe.binaries' => '/usr/bin/ffprobe',
            'timeout' => 3600
        ));
```

To create a new instance of the **ffprobe**, I use this code:
```
$ffprobe = FFMpeg\FFProbe::create(array(
                'ffmpeg.binaries' => '/usr/bin/ffmpeg',
                'ffprobe.binaries' => '/usr/bin/ffprobe', 
                'timeout' => 3600, // The timeout for the underlying process
                'ffmpeg.threads' => 1
            ));
```

When creating an instance of the **ThumbnailSprite**,
`        $sprite = new ThumbnailSprite();`

 I get this error.
```
Fatal error:  Uncaught Alchemy\BinaryDriver\Exception\ExecutableNotFoundException: Executable not found, proposed : avprobe, ffprobe in /usr/share/nginx/html/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php:159
Stack trace:
#0 /usr/share/nginx/html/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php(48): Alchemy\BinaryDriver\AbstractBinary::load(Array, NULL, Object(Alchemy\BinaryDriver\Configuration))
#1 /usr/share/nginx/html/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(226): FFMpeg\Driver\FFProbeDriver::create(Object(Alchemy\BinaryDriver\Configuration), NULL)
#2 /usr/share/nginx/html/vendor/emgag/video-thumbnail-sprite/src/ThumbnailSprite.php(277): FFMpeg\FFProbe::create()
#3 /usr/share/nginx/html/nad/model/FfmpegConv.php(850): Emgag\Video\ThumbnailSprite\ThumbnailSprite-&gt;generate()
```

All Paths are sagged correctly. And when you run the code:
```
<?php
var_dump(getenv('PATH'));
var_dump(exec('which ffmpeg'));
var_dump(ini_get('open_basedir'));
var_dump(is_file(exec('which ffmpeg')));
var_dump(is_executable(exec('which ffmpeg')));
var_dump(exec('which ffprobe'));
var_dump(exec('which avprobe'));
```
I get an answer.
```
bool(false)
string(15) "/usr/bin/ffmpeg"
string(0) ""
bool(true)
bool(true)
string(16) "/usr/bin/ffprobe"
string(16) "/usr/bin/avprobe"
```

I was not able to set the **avprobe** in the **Uubntu** and therefore I created a shortcut.
`cd /usr/bin && sudo ln ffprobe avprobe`

And my **echo $PATH** looks like this:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

What's my mistake?

**Comment by SergeyKozlov** [comment]
Its solved this problem:
You can set it:
`putenv("PATH=/usr/bin");`
